// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAs0L_EMLp_tYpqqjdY2fDoH2qTEAnZmg',
    appId: '1:567120658052:web:02bd3fe1e81fd9784accd1',
    messagingSenderId: '567120658052',
    projectId: 'techlead-57814',
    authDomain: 'techlead-57814.firebaseapp.com',
    databaseURL: 'https://techlead-57814-default-rtdb.firebaseio.com',
    storageBucket: 'techlead-57814.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9cBheiZJ20h1TslV4pVi4eUiwsxS3_o',
    appId: '1:567120658052:android:7234e24263faed6c4accd1',
    messagingSenderId: '567120658052',
    projectId: 'techlead-57814',
    databaseURL: 'https://techlead-57814-default-rtdb.firebaseio.com',
    storageBucket: 'techlead-57814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACXeAMBTpnGHAHWtFy3JwTxjxWiUUziaE',
    appId: '1:567120658052:ios:6cfb2441db8e85fe4accd1',
    messagingSenderId: '567120658052',
    projectId: 'techlead-57814',
    databaseURL: 'https://techlead-57814-default-rtdb.firebaseio.com',
    storageBucket: 'techlead-57814.firebasestorage.app',
    iosBundleId: 'com.example.techlead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACXeAMBTpnGHAHWtFy3JwTxjxWiUUziaE',
    appId: '1:567120658052:ios:6cfb2441db8e85fe4accd1',
    messagingSenderId: '567120658052',
    projectId: 'techlead-57814',
    databaseURL: 'https://techlead-57814-default-rtdb.firebaseio.com',
    storageBucket: 'techlead-57814.firebasestorage.app',
    iosBundleId: 'com.example.techlead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAs0L_EMLp_tYpqqjdY2fDoH2qTEAnZmg',
    appId: '1:567120658052:web:5a2ee490aa1406214accd1',
    messagingSenderId: '567120658052',
    projectId: 'techlead-57814',
    authDomain: 'techlead-57814.firebaseapp.com',
    databaseURL: 'https://techlead-57814-default-rtdb.firebaseio.com',
    storageBucket: 'techlead-57814.firebasestorage.app',
  );
}
